# Generated by Django 6.0.5 on 2026-06-12 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hudud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MulkTuri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(max_length=30, unique=True)),
                ('nomi', models.CharField(max_length=100)),
                ('tartib', models.PositiveIntegerField(default=0, help_text="Ro'yxatdagi tartibi")),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Mulk turi',
                'verbose_name_plural': 'Mulk turlari',
                'ordering': ['tartib', 'nomi'],
            },
        ),
        migrations.CreateModel(
            name='Viloyat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100, unique=True)),
                ('tartib', models.PositiveIntegerField(default=0, help_text="Ro'yxatdagi tartibi")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Viloyat',
                'verbose_name_plural': 'Viloyatlar',
                'ordering': ['tartib', 'nomi'],
            },
        ),
        migrations.AddField(
            model_name='hudud',
            name='viloyat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hududlar', to='hudud.viloyat'),
        ),
    ]
