# Generated by Django 6.0.5 on 2026-05-30 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hudud', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kvartira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarlavha', models.CharField(max_length=255)),
                ('tavsif', models.TextField(blank=True, null=True)),
                ('ariza_turi', models.CharField(choices=[('ijara', 'Ijaraga berish'), ('sotish', 'Sotish')], max_length=10)),
                ('xonalar_soni', models.CharField(choices=[('1', '1 xonali'), ('2', '2 xonali'), ('3', '3 xonali'), ('4', '4 xonali'), ('5+', "5 va undan ko'p")], max_length=5)),
                ('narx', models.BigIntegerField()),
                ('maydon_m2', models.FloatField(blank=True, null=True)),
                ('qavat', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('jami_qavat', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('manzil', models.CharField(blank=True, max_length=255, null=True)),
                ('holat', models.CharField(choices=[('active', 'Faol'), ('sold', 'Sotilgan/Ijarada'), ('archived', 'Arxivlangan')], default='active', max_length=10)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hudud', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kvartiralar', to='hudud.hudud')),
                ('qoshgan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kvartiralar', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kvartira',
                'verbose_name_plural': 'Kvartiralar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KvartiraRasm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.ImageField(upload_to='kvartiralar/%Y/%m/')),
                ('asosiy', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kvartira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rasmlar', to='kvartira.kvartira')),
            ],
            options={
                'verbose_name': 'Kvartira rasmi',
                'verbose_name_plural': 'Kvartira rasmlari',
            },
        ),
    ]
