# Generated by Django 6.0.5 on 2026-07-15 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hudud', '0002_mulkturi_viloyat_hudud_viloyat'),
        ('kvartira', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KvartiraPlanirovka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.ImageField(upload_to='kvartiralar/planirovka/%Y/%m/')),
                ('izoh', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Planirovka',
                'verbose_name_plural': 'Planirovkalar',
            },
        ),
        migrations.CreateModel(
            name='KvartiraSevimli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sevimli',
                'verbose_name_plural': 'Sevimlilar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='kvartira',
            options={'ordering': ['-featured', '-created_at'], 'verbose_name': 'Kvartira', 'verbose_name_plural': 'Kvartiralar'},
        ),
        migrations.AlterModelOptions(
            name='kvartirarasm',
            options={'ordering': ['-asosiy', 'tartib', 'id'], 'verbose_name': 'Kvartira rasmi', 'verbose_name_plural': 'Kvartira rasmlari'},
        ),
        migrations.AddField(
            model_name='kvartira',
            name='featured',
            field=models.BooleanField(default=False, help_text="Ko'tarilgan / Spotlight e'lon (yuqorida ko'rsatiladi)"),
        ),
        migrations.AddField(
            model_name='kvartira',
            name='featured_tugash',
            field=models.DateTimeField(blank=True, help_text="Ko'tarish (featured) muddati tugash vaqti", null=True),
        ),
        migrations.AddField(
            model_name='kvartira',
            name='hammom_soni',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Vannaxona / hammom soni', null=True),
        ),
        migrations.AddField(
            model_name='kvartira',
            name='kelishiladi',
            field=models.BooleanField(default=False, help_text='Narx kelishilgan holda (torg bor)'),
        ),
        migrations.AddField(
            model_name='kvartira',
            name='korishlar_soni',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kvartira',
            name='mebel',
            field=models.BooleanField(default=False, help_text='Mebel bilanmi'),
        ),
        migrations.AddField(
            model_name='kvartira',
            name='mulk_turi',
            field=models.ForeignKey(blank=True, help_text='Kvartira, Hovli, Ofis va h.k.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kvartiralar', to='hudud.mulkturi'),
        ),
        migrations.AddField(
            model_name='kvartira',
            name='narx_davri',
            field=models.CharField(blank=True, choices=[('oylik', 'Oyiga'), ('yillik', 'Yiliga'), ('kunlik', 'Kuniga')], help_text='Faqat ijara uchun: oylik/yillik/kunlik', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='kvartira',
            name='remont_holati',
            field=models.CharField(blank=True, choices=[('yevro', 'Yevro remont'), ('orta', "O'rta holat"), ('tamirsiz', "Ta'mirtalab"), ('yangi_bino', 'Yangi bino')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='kvartira',
            name='telefon',
            field=models.CharField(blank=True, help_text="Qo'ng'iroq uchun telefon raqami", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='kvartira',
            name='telegram_username',
            field=models.CharField(blank=True, help_text='Telegram orqali yozish uchun (masalan: @username)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kvartira',
            name='valyuta',
            field=models.CharField(choices=[('USD', '$ (dollar)'), ('UZS', "so'm")], default='UZS', help_text="Narx valyutasi — $ yoki so'm", max_length=3),
        ),
        migrations.AddField(
            model_name='kvartira',
            name='viloyat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kvartiralar', to='hudud.viloyat'),
        ),
        migrations.AddField(
            model_name='kvartirarasm',
            name='tartib',
            field=models.PositiveSmallIntegerField(default=0, help_text="Ko'rsatish tartibi"),
        ),
        migrations.AddIndex(
            model_name='kvartira',
            index=models.Index(fields=['holat', 'ariza_turi'], name='kvartira_kv_holat_9238be_idx'),
        ),
        migrations.AddIndex(
            model_name='kvartira',
            index=models.Index(fields=['-featured', '-created_at'], name='kvartira_kv_feature_b3ddcd_idx'),
        ),
        migrations.AddField(
            model_name='kvartiraplanirovka',
            name='kvartira',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planirovkalar', to='kvartira.kvartira'),
        ),
        migrations.AddField(
            model_name='kvartirasevimli',
            name='kvartira',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sevimlilar', to='kvartira.kvartira'),
        ),
        migrations.AddField(
            model_name='kvartirasevimli',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sevimli_kvartiralar', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='kvartirasevimli',
            unique_together={('user', 'kvartira')},
        ),
    ]
