# Generated by Django 6.0.5 on 2026-07-16 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kvartira', '0002_kvartiraplanirovka_kvartirasevimli_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kvartira',
            name='korishlar_soni',
        ),
        migrations.DeleteModel(
            name='KvartiraSevimli',
        ),
    ]
