# Generated by Django 6.0.5 on 2026-07-16 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvartira', '0003_remove_kvartira_korishlar_soni_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kvartira',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Xaritadagi aniq location — kenglik (lat)', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='kvartira',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Xaritadagi aniq location — uzunlik (lng)', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='kvartira',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, help_text='Telegram user ID (background) — rieltordan avtomatik olinadi', null=True),
        ),
        migrations.AlterField(
            model_name='kvartira',
            name='manzil',
            field=models.CharField(blank=True, help_text="Aniq manzil (ko'cha, uy raqami)", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='kvartira',
            name='telegram_username',
            field=models.CharField(blank=True, help_text='Telegram username (background) — @username', max_length=100, null=True),
        ),
    ]
