# Generated by Django 6.0.5 on 2026-07-21 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kvartira', '0004_kvartira_latitude_kvartira_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kvartira',
            name='kelishiladi',
        ),
    ]
