# Generated by Django 6.0.5 on 2026-07-26 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvartira', '0005_remove_kvartira_kelishiladi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kvartira',
            old_name='hammom_soni',
            new_name='sanuzellar_soni',
        ),
        migrations.AlterField(
            model_name='kvartira',
            name='sanuzellar_soni',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Sanuzellar soni', null=True),
        ),
    ]
