# Generated by Django 6.0.5 on 2026-06-02 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_username_alter_customuser_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPKode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField()),
                ('kode', models.CharField(max_length=6)),
                ('register_data', models.JSONField(default=dict)),
                ('yaratilgan_vaqt', models.DateTimeField(auto_now_add=True)),
                ('amal_qilish_vaqti', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'OTP Kode',
                'verbose_name_plural': 'OTP Kodlar',
            },
        ),
    ]
