# Generated by Django 6.0.5 on 2026-05-30 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_sarlavha', models.CharField(default='Orzuingizdagi kvartirani topamiz', max_length=255)),
                ('hero_tavsif', models.CharField(default='Professional rieltor sizga ideal variantni tanlashda yordam beradi', max_length=500)),
                ('hero_rasm', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('stat_bitimlar', models.PositiveIntegerField(default=500, help_text='500+ Bitimlar')),
                ('stat_rieltor', models.PositiveIntegerField(default=50, help_text='50+ Rieltor')),
                ('stat_javob_vaqti', models.CharField(default='2s', help_text='Javob vaqti (2s, 5min...)', max_length=10)),
                ('komissiya_foiz', models.CharField(default='1%', help_text='Faqat 1%', max_length=20)),
                ('komissiya_tavsif', models.CharField(default='Eng arzon narxlar shaharda!', max_length=255)),
                ('ustunlik_1_sarlavha', models.CharField(default='Professional tanlov', max_length=100)),
                ('ustunlik_1_tavsif', models.CharField(default='Faqat tajribali rieltorlardan tekshirilgan variantlar', max_length=255)),
                ('ustunlik_2_sarlavha', models.CharField(default='Minimal komissiya 1%', max_length=100)),
                ('ustunlik_2_tavsif', models.CharField(default="Eng yaxshi narx bo'yicha kelishishga yordam beramiz", max_length=255)),
                ('ustunlik_3_sarlavha', models.CharField(default='Yuridik tozalik', max_length=100)),
                ('ustunlik_3_tavsif', models.CharField(default='Bitim oldidan barcha hujjatlarni tekshiramiz', max_length=255)),
                ('qadam_1_sarlavha', models.CharField(default='Ariza qoldiring', max_length=100)),
                ('qadam_1_tavsif', models.CharField(default="Kvartira talablaringizni va aloqa ma'lumotlaringizni ko'rsating", max_length=255)),
                ('qadam_2_sarlavha', models.CharField(default='Variantlar tanlash', max_length=100)),
                ('qadam_2_tavsif', models.CharField(default='Rieltor sizning mezonlaringizga mos kvartilarni topadi', max_length=255)),
                ('qadam_3_sarlavha', models.CharField(default='Bitimni tuzish', max_length=100)),
                ('qadam_3_tavsif', models.CharField(default='Yuridik rasmiylashirish va hujjatlar bilan yordam beramiz', max_length=255)),
                ('rieltor_maslahati_forma', models.TextField(default='Qanchalik batafsil talablaringizni yozsangiz, ideal variantni shunchalik tezroq topamiz!')),
                ('xavfsizlik_sarlavha', models.CharField(default='Xavfsizlik kafolati', max_length=100)),
                ('xavfsizlik_tavsif', models.TextField(default="Biz faqat tekshirilgan ob'ektlar bilan ishlaymiz va barcha bitimlarning yuridik tozaligiga kafolat beramiz")),
                ('xavfsizlik_qoshimcha', models.CharField(default="Ko'chmas mulk bozorida 5 yildan ortiq", max_length=255)),
                ('tavsiya_1', models.TextField(default='Arizalarga 2 soat ichida javob bering - bu konversiyani 45% ga oshiradi')),
                ('tavsiya_2', models.TextField(default='Mijoz tanlashi uchun bir nechta kvartira variantlarini taklif qiling')),
                ('telefon', models.CharField(default='+998 99 123-45-67', max_length=20)),
                ('email', models.EmailField(default='info@kvartira.uz', max_length=254)),
                ('telegram_bot', models.CharField(default='@kvartira_bot', max_length=100)),
                ('ofis_manzil', models.CharField(default="Amir Temur ko'chasi, 1", max_length=255)),
                ('copyright_matn', models.CharField(default='© 2026 Kvartira Qidiruv. Barcha huquqlar himoyalangan', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sayt sozlamalari',
                'verbose_name_plural': 'Sayt sozlamalari',
            },
        ),
    ]
