# Generated by Django 6.0.5 on 2026-06-02 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KontaktMalumot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefon', models.CharField(default='+998 99 123-45-67', help_text='Masalan: +998 99 123-45-67', max_length=20)),
                ('email', models.EmailField(default='info@kvartira.uz', max_length=254)),
                ('telegram_bot', models.CharField(default='@kvartira_bot', help_text='Telegram bot yoki kanal nomi', max_length=100)),
                ('ofis_manzil', models.CharField(default="Amir Temur ko'chasi, 1", max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Kontakt ma'lumot",
                'verbose_name_plural': "Kontakt ma'lumot",
            },
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='email',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='ofis_manzil',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='telefon',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='telegram_bot',
        ),
    ]
