# Generated by Django 6.0.5 on 2026-06-02 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_kontaktmalumot_remove_sitesettings_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStatistika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bitimlar', models.PositiveIntegerField(default=500, help_text="Masalan: 500 → frontendda '500+' ko'rinadi")),
                ('rieltor_soni', models.PositiveIntegerField(default=50, help_text="Masalan: 50 → frontendda '50+' ko'rinadi")),
                ('javob_vaqti', models.CharField(default='2s', help_text='Javob vaqti (2s, 5min, ...)', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User statistikasi',
                'verbose_name_plural': 'User statistikasi',
            },
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='stat_bitimlar',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='stat_javob_vaqti',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='stat_rieltor',
        ),
    ]
