# Generated by Django 6.0.5 on 2026-06-02 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_userstatistika_remove_sitesettings_stat_bitimlar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderKarta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panel_turi', models.CharField(choices=[('user', 'User paneli'), ('rieltor', 'Rieltor paneli')], help_text="Qaysi panel uchun ko'rsatilsin", max_length=10)),
                ('badge_matn', models.CharField(help_text="Badge ustidagi kichik matn (masalan: 'Husma Estate', 'Rieltor paneli')", max_length=100)),
                ('sarlavha', models.CharField(blank=True, help_text="Kichik sarlavha (masalan: 'Bugungi holat') — ixtiyoriy", max_length=150, null=True)),
                ('title', models.CharField(help_text='Asosiy katta sarlavha', max_length=255)),
                ('description', models.TextField(blank=True, help_text="Qo'shimcha tavsif matni — ixtiyoriy", null=True)),
                ('tartib', models.PositiveSmallIntegerField(default=0, help_text='Sliderda tartib raqami (kichikroq = oldin chiqadi)')),
                ('faol', models.BooleanField(default=True, help_text="False qilsangiz frontendda ko'rinmaydi")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Slider kartochka',
                'verbose_name_plural': 'Slider kartochkalar',
                'ordering': ['panel_turi', 'tartib'],
            },
        ),
    ]
