# Generated by Django 5.1.4 on 2026-06-18 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_slider_default_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstatistika',
            name='bitimlar',
        ),
        migrations.RemoveField(
            model_name='userstatistika',
            name='rieltor_soni',
        ),
        migrations.AlterField(
            model_name='userstatistika',
            name='javob_vaqti',
            field=models.CharField(default='2s', help_text="O'rtacha javob vaqti (2s, 5min, ...) — admin paneldan kiritiladi", max_length=10),
        ),
    ]
