# Generated by Django 5.1.4 on 2026-06-29 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_userstatistika_remove_bitimlar_rieltor_soni'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstatistika',
            name='bitimlar_soni',
            field=models.IntegerField(default=500, help_text='Bitimlar soni — admin paneldan kiritiladi'),
        ),
        migrations.AddField(
            model_name='userstatistika',
            name='rieltorlar_soni',
            field=models.IntegerField(default=50, help_text='Rieltorlar soni — admin paneldan kiritiladi'),
        ),
    ]
