# Generated by Django 6.0.5 on 2026-05-30 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hudud', '0001_initial'),
        ('makler', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ariza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ariza_turi', models.CharField(choices=[('ijara', 'Ijaraga olish'), ('sotib_olish', 'Sotib olish')], max_length=15)),
                ('xonalar_soni', models.CharField(choices=[('1', '1 xonali'), ('2', '2 xonali'), ('3', '3 xonali'), ('4', '4 xonali'), ('5+', "5 va undan ko'p")], max_length=5)),
                ('narx_min', models.BigIntegerField()),
                ('narx_max', models.BigIntegerField()),
                ('telefon', models.CharField(blank=True, max_length=20, null=True)),
                ('qoshimcha_izoh', models.TextField(blank=True, null=True)),
                ('holat', models.CharField(choices=[('yangi', 'Yangi'), ('korilmoqda', "Ko'rilmoqda"), ('yopilgan', 'Yopilgan')], default='yangi', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hudud', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arizalar', to='hudud.hudud')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arizalar', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ariza',
                'verbose_name_plural': 'Arizalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArizaMakler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holat', models.CharField(choices=[('yuborildi', 'Yuborildi'), ('korildi', "Ko'rildi"), ('boglandi', "Bog'landi"), ('yopildi', 'Yopildi')], default='yuborildi', max_length=15)),
                ('korilgan_vaqt', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ariza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ariza_maklerlar', to='ariza.ariza')),
                ('makler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ariza_maklerlar', to='makler.maklerprofil')),
            ],
            options={
                'verbose_name': 'Ariza-Makler',
                'verbose_name_plural': 'Ariza-Maklerlar',
                'unique_together': {('ariza', 'makler')},
            },
        ),
    ]
