# Generated by Django 6.0.5 on 2026-06-12 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ariza', '0003_rename_ariza_makler_fields'),
        ('hudud', '0002_mulkturi_viloyat_hudud_viloyat'),
        ('makler', '0004_maklerprofil_mulk_turlari'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arizamakler',
            options={'verbose_name': 'Ariza-Rieltor', 'verbose_name_plural': 'Ariza-Rieltorlar'},
        ),
        migrations.AddField(
            model_name='ariza',
            name='mulk_turi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arizalar', to='hudud.mulkturi'),
        ),
        migrations.AddField(
            model_name='ariza',
            name='viloyat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arizalar', to='hudud.viloyat'),
        ),
        migrations.AlterField(
            model_name='arizamakler',
            name='ariza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ariza_rieltorlar', to='ariza.ariza'),
        ),
        migrations.AlterField(
            model_name='arizamakler',
            name='rieltor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ariza_rieltorlar', to='makler.maklerprofil'),
        ),
    ]
