# Generated by Django 6.0.5 on 2026-07-27 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ariza', '0004_alter_arizamakler_options_ariza_mulk_turi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ariza',
            name='valyuta',
            field=models.CharField(choices=[('UZS', "so'm"), ('USD', '$ (dollar)')], default='UZS', help_text="Narx valyutasi — so'm yoki $", max_length=3),
        ),
    ]
