# Generated by Django 6.0.5 on 2026-07-29 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ariza', '0005_ariza_valyuta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ariza',
            name='ariza_turi',
            field=models.CharField(choices=[('ijara', 'Ijaraga olish'), ('sotib_olish', 'Sotib olish'), ('ijara_berish', 'Ijaraga berish'), ('sotish', 'Sotish')], max_length=15),
        ),
        migrations.AlterField(
            model_name='ariza',
            name='narx_max',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ariza',
            name='xonalar_soni',
            field=models.CharField(choices=[('1', '1 xonali'), ('2', '2 xonali'), ('3', '3 xonali'), ('4+', '4+ xonali')], default='1', max_length=5),
        ),
    ]
