# Generated by Django 6.0.5 on 2026-05-30 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hudud', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaklerProfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True)),
                ('telegram_link', models.CharField(blank=True, max_length=100, null=True)),
                ('verify_holat', models.CharField(choices=[('pending', 'Kutilmoqda'), ('verified', 'Tasdiqlangan'), ('rejected', 'Rad etilgan')], default='pending', max_length=10)),
                ('verify_qilingan_vaqt', models.DateTimeField(blank=True, null=True)),
                ('ortacha_reyting', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('jami_bitimlar', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hududlar', models.ManyToManyField(blank=True, related_name='maklerlar', to='hudud.hudud')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='makler_profil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Makler profil',
                'verbose_name_plural': 'Makler profillari',
            },
        ),
    ]
