# Generated by Django 6.0.5 on 2026-06-04 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hudud', '0001_initial'),
        ('makler', '0002_rename_makler_to_rieltor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maklerprofil',
            options={'verbose_name': 'Rieltor profil', 'verbose_name_plural': 'Rieltor profillari'},
        ),
        migrations.AddField(
            model_name='maklerprofil',
            name='bepul_muddat_tugash',
            field=models.DateTimeField(blank=True, help_text="Bepul sinov muddati tugash vaqti (ro'yxatdan o'tgandan 7 kun)", null=True),
        ),
        migrations.AddField(
            model_name='maklerprofil',
            name='obuna_faol',
            field=models.BooleanField(default=False, help_text="To'liq obuna faolmi (keyinchalik qo'shiladi)"),
        ),
        migrations.AddField(
            model_name='maklerprofil',
            name='obuna_tugash',
            field=models.DateTimeField(blank=True, help_text="Obuna tugash vaqti (keyinchalik qo'shiladi)", null=True),
        ),
        migrations.AlterField(
            model_name='maklerprofil',
            name='hududlar',
            field=models.ManyToManyField(blank=True, related_name='rieltorlar', to='hudud.hudud'),
        ),
        migrations.AlterField(
            model_name='maklerprofil',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rieltor_profil', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='maklerprofil',
            name='verify_holat',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('verified', 'Tasdiqlangan'), ('rejected', 'Rad etilgan')], default='verified', max_length=10),
        ),
    ]
