# Generated by Django 6.0.5 on 2026-06-12 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hudud', '0002_mulkturi_viloyat_hudud_viloyat'),
        ('makler', '0003_add_obuna_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='maklerprofil',
            name='mulk_turlari',
            field=models.ManyToManyField(blank=True, help_text='Rieltor qaysi mulk turlari bilan ishlaydi', related_name='rieltorlar', to='hudud.mulkturi'),
        ),
    ]
