# Generated by Django 5.1.4 on 2026-06-13 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makler', '0004_maklerprofil_mulk_turlari'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maklerprofil',
            name='obuna_faol',
        ),
        migrations.RemoveField(
            model_name='maklerprofil',
            name='obuna_tugash',
        ),
        migrations.AlterField(
            model_name='maklerprofil',
            name='verify_holat',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('verified', 'Tasdiqlangan'), ('rejected', 'Bloklangan')], default='verified', help_text="Admin moderatsiya holati. 'Bloklangan' (rejected) qilinsa, obuna/bepul muddatidan qat'i nazar rieltor ishlay olmaydi.", max_length=10),
        ),
    ]
