# Generated by Django 5.1.4 on 2026-07-26 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makler', '0006_qoshimcha_bepul_muddat'),
    ]

    operations = [
        migrations.AddField(
            model_name='maklerprofil',
            name='promo_xabar_vaqti',
            field=models.DateTimeField(blank=True, help_text='Promo (aksiya) xabari qachon yuborilgani (audit uchun)', null=True),
        ),
        migrations.AddField(
            model_name='maklerprofil',
            name='promo_xabar_yuborildi',
            field=models.BooleanField(default=False, help_text='Bepul muddat tugagach obuna promo (aksiya) xabari yuborilganmi'),
        ),
    ]
