# Generated by Django 6.0.5 on 2026-07-28 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makler', '0007_maklerprofil_promo_xabar_vaqti_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maklerprofil',
            name='telegram_bloklangan',
            field=models.BooleanField(default=False, help_text="Bot bloklangan yoki foydalanuvchi /start bosmagan. True bo'lsa xabar yuborilmaydi.", verbose_name='Telegram bloklangan'),
        ),
        migrations.AddField(
            model_name='maklerprofil',
            name='telegram_bloklangan_vaqt',
            field=models.DateTimeField(blank=True, help_text='telegram_bloklangan=True qilingan vaqt (audit uchun)', null=True, verbose_name='Bloklangan vaqti'),
        ),
    ]
