# Generated by Django 5.1.4 on 2026-06-13 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('makler', '0005_remove_maklerprofil_obuna_faol_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(help_text="Masalan: 'Oylik obuna'", max_length=100)),
                ('kod', models.SlugField(help_text="Texnik kod, masalan: 'oylik', 'yillik'", unique=True)),
                ('narx', models.PositiveIntegerField(help_text="So'mda")),
                ('davomiylik_kun', models.PositiveIntegerField(help_text='Obuna necha kun amal qiladi (masalan: 30, 90, 365)')),
                ('izoh', models.TextField(blank=True, null=True)),
                ('tartib', models.PositiveSmallIntegerField(default=0, help_text="Ro'yxatdagi tartibi (kichikroq = oldin)")),
                ('is_active', models.BooleanField(default=True, help_text="False bo'lsa frontendda ko'rinmaydi va sotib olib bo'lmaydi")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tarif',
                'verbose_name_plural': 'Tariflar',
                'ordering': ['tartib', 'narx'],
            },
        ),
        migrations.CreateModel(
            name='Obuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holat', models.CharField(choices=[('kutilmoqda', "To'lov kutilmoqda"), ('faol', 'Faol'), ('tugagan', 'Muddati tugagan'), ('bekor', 'Bekor qilingan')], default='kutilmoqda', max_length=15)),
                ('narx', models.PositiveIntegerField(help_text="Sotib olingan paytdagi narx (so'm)")),
                ('boshlanish_vaqti', models.DateTimeField(blank=True, null=True)),
                ('tugash_vaqti', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rieltor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obunalar', to='makler.maklerprofil')),
                ('tarif', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='obunalar', to='obuna.tarif')),
            ],
            options={
                'verbose_name': 'Obuna',
                'verbose_name_plural': 'Obunalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tolov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provayder', models.CharField(choices=[('payme', 'Payme'), ('click', 'Click'), ('manual', "Qo'lda (admin)")], default='manual', max_length=10)),
                ('summa', models.PositiveIntegerField(help_text="To'lov summasi (so'm)")),
                ('holat', models.CharField(choices=[('kutilmoqda', 'Kutilmoqda'), ('muvaffaqiyatli', 'Muvaffaqiyatli'), ('bekor', 'Bekor qilingan'), ('xato', 'Xato')], default='kutilmoqda', max_length=15)),
                ('tashqi_id', models.CharField(blank=True, help_text='Payme/Click tranzaksiya identifikatori', max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('tolangan_vaqt', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('obuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tolovlar', to='obuna.obuna')),
            ],
            options={
                'verbose_name': "To'lov",
                'verbose_name_plural': "To'lovlar",
                'ordering': ['-created_at'],
            },
        ),
    ]
