# Generated by Django 5.1.4 on 2026-06-13 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obuna', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymeTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payme_id', models.CharField(help_text='Payme tomonidagi tranzaksiya identifikatori', max_length=255, unique=True)),
                ('amount', models.BigIntegerField(help_text='Summa (tiyin)')),
                ('state', models.IntegerField(default=1)),
                ('reason', models.IntegerField(blank=True, help_text='Bekor qilish sababi kodi (Payme)', null=True)),
                ('create_time', models.BigIntegerField(default=0)),
                ('perform_time', models.BigIntegerField(default=0)),
                ('cancel_time', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tolov', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payme_transaction', to='obuna.tolov')),
            ],
            options={
                'verbose_name': 'Payme tranzaksiya',
                'verbose_name_plural': 'Payme tranzaksiyalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
