# Generated by Django 5.1.4 on 2026-06-19 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obuna', '0002_paymetransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tolov',
            name='provayder',
            field=models.CharField(choices=[('payme', 'Payme'), ('click', 'Click'), ('manual', "Qo'lda (admin)"), ('multicard', 'Multicard')], default='manual', max_length=10),
        ),
    ]
