# Generated by Django 5.1.4 on 2026-07-26 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obuna', '0005_tarif_asl_narx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarif',
            name='narx',
            field=models.PositiveIntegerField(help_text="Haqiqatda to'lanadigan narx (so'mda). Chegirma bo'lsa — chegirmali narx."),
        ),
    ]
